//
//  HomeWorker.swift
//  teste-solutis
//
//  Created by Virtual Machine on 15/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Foundation
import KeychainSwift

class HomeWorker {

    private let validation = ValidationUtils()
    private let statementService = StatementService()

    func fetchStatements(token: String, completionHandler: @escaping (Result<[StatementModel], Error>) -> Void) {
        statementService.fetchStatements(token: token) { result in
            completionHandler(result)
        }
    }
}
