//
//  HomeInteractor.swift
//  teste-solutis
//
//  Created by Virtual Machine on 15/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic {
    func displayUser(request: Home.DisplayUser.Request)
    func fetchStatements(request: Home.FetchStatements.Request)
}

class HomeInteractor: HomeBusinessLogic {
    
    var presenter: HomePresentationLogic?
    var worker: HomeWorker?
    
    func displayUser(request: Home.DisplayUser.Request) {
        let response = Home.DisplayUser.Response(user: request.user)
        presenter?.presentUser(response: response)
    }
    
    func fetchStatements(request: Home.FetchStatements.Request) {
        worker = HomeWorker()
        worker?.fetchStatements()
        
        // Present
    }
}
