//
//  HomePresenter.swift
//  teste-solutis
//
//  Created by Virtual Machine on 15/09/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentUser(user: UserModel)
    func presentStatements(response: HomeModels.FetchStatements.Response)
    func presentError(error: Error)
}

class HomePresenter: HomePresentationLogic {
    
    var controller: HomeDisplayLogic?
    
    func presentUser(user: UserModel) {
        controller?.displayUser(viewModel: HomeModels.DisplayUser.ViewModel(user: user))
    }
    
    func presentStatements(response: HomeModels.FetchStatements.Response) {
        
    }
    
    func presentError(error: Error) {
        
    }
}
